server:
  port: 8080
spring:
  application:
    name: MultiTenant
  datasource:
    url: 'jdbc:postgresql://localhost:5432/codingworld?ApplicationName=MultiTenant'
    username: 'postgres'
    password: 'postgres'
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
  main:
    allow-circular-references: true